// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "wavynote",
            "email": "chelseafandev@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/box/conversation": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 대화방 삭제",
                "tags": [
                    "받은노트 페이지"
                ],
                "summary": "특정 대화방 삭제",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "cid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/box/conversationlist": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "노트를 주고 받는 대화방 목록 조회(최대 3개)",
                "tags": [
                    "받은노트 페이지"
                ],
                "summary": "노트를 주고 받는 대화방 목록 조회(최대 3개)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "조회된 대화방 목록 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.ConversationListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/box/notelist": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 친구와 주고받은 노트 목록",
                "tags": [
                    "받은노트 페이지"
                ],
                "summary": "특정 친구와 주고받은 노트 목록",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "주고 받은 노트 목록",
                        "schema": {
                            "$ref": "#/definitions/restapi.ConverstaionNoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/box/show": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 노트 조회",
                "tags": [
                    "받은노트 페이지"
                ],
                "summary": "특정 노트 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "cid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "note id",
                        "name": "nid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "조회한 노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteInfo"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/main/folder": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 폴더 이름 변경",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "특정 폴더 이름 변경",
                "parameters": [
                    {
                        "description": "변경하고자 하는 폴더 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.ChangeFolderNameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "폴더 추가",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "폴더 추가",
                "parameters": [
                    {
                        "description": "추가할 폴더 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.AddFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 폴더 삭제",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "특정 폴더 삭제",
                "parameters": [
                    {
                        "description": "삭제할 폴더 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.RemoveFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/main/folderlist": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "존재하는 모든 폴더 목록 조회",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "존재하는 모든 폴더 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "폴더 목록 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.FolderListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/main/note": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 특정 노트 삭제",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 특정 노트 삭제",
                "parameters": [
                    {
                        "description": "삭제할 노트 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.RemoveNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/main/notefolder": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "노트가 저장되는 폴더 변경",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "노트가 저장되는 폴더 변경",
                "parameters": [
                    {
                        "description": "노트를 저장할 (변경할)폴더 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.ChangeNoteFolderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/main/notelist": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 폴더에 존재하는 모든 노트 조회",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "특정 폴더에 존재하는 모든 노트 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "folder id",
                        "name": "fid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "노트 목록 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/opennote/list": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "사용자 키워드 기반으로 오픈노트에 공유된 노트 목록 조회",
                "tags": [
                    "오픈노트 페이지"
                ],
                "summary": "사용자 키워드 기반으로 오픈노트에 공유된 노트 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "오픈노트에 공유된 노트 목록",
                        "schema": {
                            "$ref": "#/definitions/restapi.OpenNoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/opennote/show": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 오픈노트 조회",
                "tags": [
                    "오픈노트 페이지"
                ],
                "summary": "특정 오픈노트 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "note id",
                        "name": "nid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "conversation id",
                        "name": "cid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "조회한 오픈노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteInfo"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/profile/duplicate": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "회원 가입 시 ID 중복 체크",
                "tags": [
                    "SignUp/SignIn 페이지"
                ],
                "summary": "회원 가입 시 ID 중복 체크",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/profile/signin": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "로그인 요청",
                "tags": [
                    "SignUp/SignIn 페이지"
                ],
                "summary": "로그인 요청",
                "parameters": [
                    {
                        "description": "로그인 요청",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "랜딩페이지 출력 시 필요한 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.LandingPageResonse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/profile/signup": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "회원 가입 요청",
                "tags": [
                    "SignUp/SignIn 페이지"
                ],
                "summary": "회원 가입 요청",
                "parameters": [
                    {
                        "description": "회원 가입 요청 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "랜딩페이지 출력 시 필요한 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.LandingPageResonse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/search/folder": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "특정 폴더를 대상으로 노트 검색",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "특정 폴더를 대상으로 노트 검색",
                "parameters": [
                    {
                        "type": "string",
                        "description": "target folder id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "query for search",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "검색어가 포함된 노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/search/opennote": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "오픈노트 대상으로 노트 내용 검색",
                "tags": [
                    "오픈노트 페이지"
                ],
                "summary": "오픈노트 대상으로 노트 내용 검색",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query for search",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "검색어가 포함된 오픈노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.OpenNoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/search/top": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "전체 폴더를 대상으로 노트 내용 검색",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "전체 폴더를 대상으로 노트 내용 검색",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "query for search",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "검색어가 포함된 노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteListResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/write/opennote": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트를 오픈 노트에 공유하기",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트를 오픈 노트에 공유하기",
                "parameters": [
                    {
                        "description": "오픈 노트에 공유를 위한 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.ShareNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/write/random": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트를 랜덤 매칭을 통해 (비슷한 관심 주제를 갖는)임의의 대상에게 보내기",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트를 랜덤 매칭을 통해 (비슷한 관심 주제를 갖는)임의의 대상에게 보내기",
                "parameters": [
                    {
                        "description": "랜덤 매칭을 통해 보낼 노트 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.RandomMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/write/save": {
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트 갱신",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트 갱신",
                "parameters": [
                    {
                        "description": "갱신할 노트 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.UpdateNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트 저장",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트 저장",
                "parameters": [
                    {
                        "description": "저장할 노트 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.SaveNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/write/send": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트를 특정 대상에게 보내기",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트를 특정 대상에게 보내기",
                "parameters": [
                    {
                        "description": "특정 대상에게 보낼 노트 정보",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/restapi.SendNoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.DefaultResponse"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        },
        "/write/show": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "내가 작성한 노트 조회",
                "tags": [
                    "나의노트 페이지"
                ],
                "summary": "내가 작성한 노트 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "note id",
                        "name": "nid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "내가 작성한 노트 정보",
                        "schema": {
                            "$ref": "#/definitions/restapi.NoteInfo"
                        }
                    },
                    "400": {
                        "description": "요청에 포함된 파라미터 값이 잘못된 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response400"
                        }
                    },
                    "401": {
                        "description": "인증에 실패한 경우이며, 실패 사유가 전달됩니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response401"
                        }
                    },
                    "404": {
                        "description": "요청한 리소스가 서버에 존재하지 않는 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response404"
                        }
                    },
                    "500": {
                        "description": "요청을 처리하는 과정에서 서버에 문제가 발생한 경우입니다",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "restapi.AddFolderRequest": {
            "type": "object",
            "properties": {
                "folder_name": {
                    "description": "추가할 폴더 이름",
                    "type": "string",
                    "example": "my wavywavy"
                },
                "user_id": {
                    "description": "사용자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                }
            }
        },
        "restapi.ChangeFolderNameRequest": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "이름을 변경할 폴더의 고유 id 값",
                    "type": "string",
                    "example": "a3106a0c-5ce7-40f6-81f4-ff9b8ebb240b"
                },
                "folder_name": {
                    "description": "변경할 폴더 이름",
                    "type": "string",
                    "example": "whatever"
                },
                "user_id": {
                    "description": "이름을 변경할 폴더를 소유하고 있는 사용자 ID",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                }
            }
        },
        "restapi.ChangeNoteFolderRequest": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "노트가 저장되는 폴더의 고유 id 값",
                    "type": "string",
                    "example": "980e71ba-0395-49aa-833e-3ebc76b3ec88"
                },
                "notes": {
                    "description": "폴더를 변경할 노트의 고유 id 값",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "09d05df1-2958-4a3d-b910-3b4fb079327b"
                    ]
                },
                "user_id": {
                    "description": "사용자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                }
            }
        },
        "restapi.ConversationInfo": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "description": "대화방 고유의 id 값",
                    "type": "string",
                    "example": "1afc571d-61bf-4cef-95ce-ab791f999297"
                },
                "new_note": {
                    "description": "대화방에 읽지않은 노트가 존재하는지 여부",
                    "type": "boolean",
                    "example": true
                },
                "note_count": {
                    "description": "대화방에 존재하는 노트의 총 개수",
                    "type": "integer",
                    "example": 20
                },
                "opp_nickname": {
                    "description": "대화 상대의 별명",
                    "type": "string",
                    "example": "somebody"
                }
            }
        },
        "restapi.ConversationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.ConversationInfo"
                    }
                }
            }
        },
        "restapi.ConversationNoteInfo": {
            "type": "object",
            "properties": {
                "from_id": {
                    "description": "노트 송신자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "note_id": {
                    "description": "노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "preview": {
                    "description": "노트 본문 미리보기",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "send_at": {
                    "description": "노트 전송 시간",
                    "type": "string",
                    "example": "2023-10-29 21:00:48"
                },
                "title": {
                    "description": "노트 제목",
                    "type": "string",
                    "example": "my first note"
                },
                "to_id": {
                    "description": "노트 수신자 id",
                    "type": "string",
                    "example": "somebody@naver.com"
                }
            }
        },
        "restapi.ConverstaionNoteListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.ConversationNoteInfo"
                    }
                }
            }
        },
        "restapi.DefaultResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "description": "실패 시 반환하는 에러 메시지",
                    "type": "string"
                },
                "result": {
                    "description": "요청에 대한 처리 성공/실패 여부",
                    "type": "string",
                    "example": "true"
                }
            }
        },
        "restapi.FolderListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.FolderSimpleInfo"
                    }
                }
            }
        },
        "restapi.FolderSimpleInfo": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "폴더의 고유 id 값",
                    "type": "string",
                    "example": "a3106a0c-5ce7-40f6-81f4-ff9b8ebb240b"
                },
                "folder_name": {
                    "description": "폴더 이름",
                    "type": "string",
                    "example": "my diary"
                },
                "note_count": {
                    "description": "폴더에 존재하는 노트의 총 개수",
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "restapi.LandingPageResonse": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "랜딩 페이지에서 보여줄 폴더의 고유 id 값",
                    "type": "string",
                    "example": "283744fe-7074-4ffa-abc6-dae8cb786058"
                },
                "user_id": {
                    "description": "사용자 id",
                    "type": "string",
                    "example": "somebody@naver.com"
                }
            }
        },
        "restapi.NoteInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "노트의 본문 내용",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "conversation_id": {
                    "description": "대화방의 고유 id 값",
                    "type": "string",
                    "example": "1afc571d-61bf-4cef-95ce-ab791f999297"
                },
                "folder_id": {
                    "description": "노트가 포함되어 있는 폴더의 고유 id 값",
                    "type": "string",
                    "example": "980e71ba-0395-49aa-833e-3ebc76b3ec88"
                },
                "from_id": {
                    "description": "노트 작성자(또는 송신자)의 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "keywords": {
                    "description": "노트의 키워드",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "b0d88d67-01fd-47f8-b426-6ca0657d0f6e"
                    ]
                },
                "note_id": {
                    "description": "노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "save_at": {
                    "description": "노트를 저장한 마지막 날짜 및 시간 정보",
                    "type": "string",
                    "example": "2023-11-01 21:00:00"
                },
                "send_at": {
                    "description": "노트를 송신한 날짜 및 시간 정보",
                    "type": "string",
                    "example": "2023-11-01 23:20:12"
                },
                "title": {
                    "description": "노트의 제목",
                    "type": "string",
                    "example": "my first note"
                },
                "to_id": {
                    "description": "노트 수신자의 id",
                    "type": "string",
                    "example": "somebody@naver.com"
                }
            }
        },
        "restapi.NoteListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.NoteSimpleInfo"
                    }
                }
            }
        },
        "restapi.NoteSimpleInfo": {
            "type": "object",
            "properties": {
                "note_id": {
                    "description": "해당 폴더에 존재하는 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "preview": {
                    "description": "해당 폴더에 존재하는 노트의 본문 미리보기(글자수 제한)",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "title": {
                    "description": "해당 폴더에 존재하는 노트의 제목",
                    "type": "string",
                    "example": "my first note"
                }
            }
        },
        "restapi.OpenNoteListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.OpenNoteSimpleInfo"
                    }
                }
            }
        },
        "restapi.OpenNoteSimpleInfo": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "description": "오픈 노트 공유를 통해 생성된 대화방 고유 id 값",
                    "type": "string",
                    "example": "1afc571d-61bf-4cef-95ce-ab791f999297"
                },
                "note_id": {
                    "description": "오픈 노트에 공유한 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "post_at": {
                    "description": "오픈 노트에 공유한 시간",
                    "type": "string",
                    "example": "2023-12-19 15:55:48"
                },
                "preview": {
                    "description": "오픈 노트에 공유한 노트의 본문 미리보기",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "title": {
                    "description": "오픈 노트에 공유한 노트의 제목",
                    "type": "string",
                    "example": "my first note"
                }
            }
        },
        "restapi.RandomMatchRequest": {
            "type": "object",
            "properties": {
                "from_id": {
                    "description": "노트를 보내는 사용자의 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "note_id": {
                    "description": "랜덤 매칭을 통해 임의의 대상에게 보낼 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                }
            }
        },
        "restapi.RemoveFolderInfo": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "삭제할 폴더의 고유 id 값",
                    "type": "string",
                    "example": "a3106a0c-5ce7-40f6-81f4-ff9b8ebb240b"
                },
                "folder_name": {
                    "description": "삭제할 폴더의 이름",
                    "type": "string",
                    "example": "my diary"
                }
            }
        },
        "restapi.RemoveFolderRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.RemoveFolderInfo"
                    }
                },
                "user_id": {
                    "description": "사용자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                }
            }
        },
        "restapi.RemoveNoteInfo": {
            "type": "object",
            "properties": {
                "folder_id": {
                    "description": "삭제할 노트가 포함되어 있는 폴더의 고유 id 값",
                    "type": "string",
                    "example": "980e71ba-0395-49aa-833e-3ebc76b3ec88"
                },
                "note_id": {
                    "description": "삭제할 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                }
            }
        },
        "restapi.RemoveNoteRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/restapi.RemoveNoteInfo"
                    }
                },
                "user_id": {
                    "description": "사용자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                }
            }
        },
        "restapi.Response400": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "msg": {
                    "type": "string",
                    "example": "Bad request"
                }
            }
        },
        "restapi.Response401": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 401
                },
                "msg": {
                    "type": "string",
                    "example": "Fail to parse Authorization header"
                }
            }
        },
        "restapi.Response404": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "msg": {
                    "type": "string",
                    "example": "Not exist the target resource in our server"
                }
            }
        },
        "restapi.Response500": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "msg": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "restapi.SaveNoteRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "내가 작성한 노트의 본문 내용",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "folder_id": {
                    "description": "내가 작성한 노트가 포함되어 있는 폴더의 고유 id 값",
                    "type": "string",
                    "example": "980e71ba-0395-49aa-833e-3ebc76b3ec88"
                },
                "from_id": {
                    "description": "작성자의 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "keywords": {
                    "description": "내가 작성한 노트의 키워드",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "b0d88d67-01fd-47f8-b426-6ca0657d0f6e"
                    ]
                },
                "title": {
                    "description": "내가 작성한 노트의 제목",
                    "type": "string",
                    "example": "my first note"
                }
            }
        },
        "restapi.SendNoteRequest": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "description": "대화방의 고유 id 값",
                    "type": "string",
                    "example": "1afc571d-61bf-4cef-95ce-ab791f999297"
                },
                "from_id": {
                    "description": "작성자의 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "note_id": {
                    "description": "내가 작성한 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "to_id": {
                    "description": "내가 작성한 노트를 보내는 대상의 id",
                    "type": "string",
                    "example": "somebody@naver.com"
                }
            }
        },
        "restapi.ShareNoteRequest": {
            "type": "object",
            "properties": {
                "host_id": {
                    "description": "오픈 노트에 공유한 사용자 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "note_id": {
                    "description": "오픈 노트에 공유할 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                }
            }
        },
        "restapi.SignInRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "로그인시 입력한 ID",
                    "type": "string",
                    "example": "somebody@naver.com"
                },
                "password": {
                    "description": "로그인시 입력한 패스워드",
                    "type": "string",
                    "example": "04F0BF9AB5963706415A0EC4C0E8167EBC8640B0B9A40870CDC39BE8A8DA813B"
                }
            }
        },
        "restapi.SignUpRequest": {
            "type": "object",
            "properties": {
                "emoji": {
                    "description": "회원 가입시 입력한 이모지",
                    "type": "string",
                    "example": "😎"
                },
                "id": {
                    "description": "회원 가입시 입력한 ID",
                    "type": "string",
                    "example": "somebody@naver.com"
                },
                "keywords": {
                    "description": "회원 가입시 입력한 키워드",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "b0d88d67-01fd-47f8-b426-6ca0657d0f6e"
                    ]
                },
                "nickname": {
                    "description": "회원 가입시 입력한 닉네임",
                    "type": "string",
                    "example": "somebody"
                },
                "password": {
                    "description": "회원 가입시 입력한 패스워드",
                    "type": "string",
                    "example": "04F0BF9AB5963706415A0EC4C0E8167EBC8640B0B9A40870CDC39BE8A8DA813B"
                }
            }
        },
        "restapi.UpdateNoteRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "내가 작성한 노트의 본문 내용",
                    "type": "string",
                    "example": "This is the main text of my first wavy note."
                },
                "folder_id": {
                    "description": "내가 작성한 노트가 포함되어 있는 폴더의 고유 id 값",
                    "type": "string",
                    "example": "980e71ba-0395-49aa-833e-3ebc76b3ec88"
                },
                "from_id": {
                    "description": "작성자의 id",
                    "type": "string",
                    "example": "wavynoteadmin@gmail.com"
                },
                "keywords": {
                    "description": "내가 작성한 노트의 키워드",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "b0d88d67-01fd-47f8-b426-6ca0657d0f6e"
                    ]
                },
                "note_id": {
                    "description": "내가 작성한 노트의 고유 id 값",
                    "type": "string",
                    "example": "09d05df1-2958-4a3d-b910-3b4fb079327b"
                },
                "title": {
                    "description": "내가 작성한 노트의 제목",
                    "type": "string",
                    "example": "my first note"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
